# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

# map paths
map_path: './example_map'
map_path: './f1tenth_racetracks/MoscowRaceway/MoscowRaceway_map'
#map_path: './f1tenth_racetracks/Austin/Austin_map'
#map_path: './CPSWeekTrack'
map_ext: '.png'

# starting pose for map
#example
#sx: 30.0
#sy: 17.0
sx: 0
sy: 0
# sx: -54.0
# sy: -16.0
#Austin, MexicoCity, Monza, MoscowRaceway, Nuerburgring
stheta: -2.
#BrandsHatch, Catalunya
#stheta: 0.7079632679
#Hockenheim
# stheta: -1.7079632679
#IMS, Melbourne
#stheta: -0.7079632679
#Montreal
# sx: 0.65
# sy: -1.5
# stheta: -1.7079632679
#cps
# sx: 0.7
# sy: -3.0
# stheta: 3.7079632679
#Sochi


# raceline path and indices
wpt_path: './example_waypoints.csv'
wpt_path: './f1tenth_racetracks/MoscowRaceway/MoscowRaceway_raceline.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345
